---
apiVersion: v1
kind: Namespace
metadata:
  name: dex
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: dex
  namespace: kube-system
spec:
  repo: https://charts.dexidp.io
  chart: dex
  targetNamespace: dex
  valuesContent: |-
    config:
      # Set it to a valid URL
      issuer: https://dex-demo.nabokikh.hf.flant.com

      # See https://dexidp.io/docs/storage/ for more options
      storage:
        type: kubernetes
        config:
          inCluster: true

      connectors:
      - type: oidc
        # Required field for connector id.
        id: gitlab
        # Required field for connector name.
        name: GitLab
        config:
          # optional, default = https://gitlab.com
          issuer: https://gitlab.com
          # Credentials can be string literals or pulled from the environment.
          clientID: xxx
          clientSecret: xxx
          redirectURI: https://dex-demo.nabokikh.hf.flant.com/callback
          # Optional groups whitelist, communicated through the "groups" scope.
          # If `groups` is omitted, all of the user's GitLab groups are returned when the groups scope is present.
          # If `groups` is provided, this acts as a whitelist - only the user's GitLab groups that are in the configured `groups` below will go into the groups claim.  Conversely, if the user is not in any of the configured `groups`, the user will not be authenticated.
          allowedGroups:
          - my-test-group-i-will-delete
          insecureEnableGroups: true
          scopes: [read_user, openid]

          # mapping of fields from the submitted token
          userNameKey: sub
          claimMapping:
            email: user_email
            groups: groups_direct

          insecureSkipEmailVerified: true

      logger:
        format: "json"

      staticClients:
      - id: example-app
        redirectURIs:
        - 'http://127.0.0.1:5555/callback'
        - '/device/callback'
        name: 'Example App'
        secret: ZXhhbXBsZS1hcHAtc2VjcmV0

      expiry:
        refreshTokens:
          disableRotation: true
          reuseInterval: 2m

    ingress:
      enabled: true
      hosts:
      - host: dex-demo.nabokikh.hf.flant.com
        paths:
        - path: /
          pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: acme
      tls:
      - hosts:
        - dex-demo.nabokikh.hf.flant.com
        secretName: dex-cert
